import manifest from "../../public/assets/logo/logo.manifest.json";
import type { LogoArm } from "@/design-system/brand/geometry";
import type { LogoTone, LogoVariant } from "@/design-system/components/brand/Logo";

/**
 * The brand asset inventory.
 *
 * Generated by `scripts/build-logo-assets.mjs` alongside the files themselves,
 * so the page can never list an asset that was not written. Nothing here is
 * hand-maintained — re-run `npm run assets:logo` after changing the generator.
 */

export interface LogoAssetLockup {
  id: string;
  label: string;
  /** Which live `<Logo>` renders the specimen for this file. */
  variant: LogoVariant;
  tone: LogoTone;
  file: string;
  width: number;
  height: number;
  bytes: number;
}

export interface LogoAssetIcon {
  file: string;
  size: number;
  use: string;
}

export interface LogoBrand {
  id: string;
  name: string;
  /** The parent (wordmark alone), a process, or the Okwe Knowledge imprint. */
  kind: "parent" | "process" | "imprint";
  /** Set for a process only; `null` for the parent and the imprint. */
  arm: LogoArm | null;
  note: string;
  lockups: LogoAssetLockup[];
  icons: LogoAssetIcon[];
}

export interface SharedAsset {
  file: string;
  label: string;
  bytes: number;
}

export interface LogoManifest {
  note: string;
  generatedBy: string;
  /** The logo rule, in full. Shown on the page and written into the kit. */
  rule: string;
  brands: LogoBrand[];
  shared: SharedAsset[];
}

export const LOGO_MANIFEST = manifest as LogoManifest;

/** Where the generated files are served from. */
export const LOGO_DIR = "/assets/logo";
export const assetUrl = (file: string) => `${LOGO_DIR}/${file}`;

/** Bytes as a short human figure for the ledger's annotation margin. */
export function readableBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  return `${Math.round(bytes / 1024)} KB`;
}

export const BRAND_INTRO = {
  code: "OKW-BRAND-01",
  title: "Brand assets",
  lede: "Every mark for Okwe, its three processes — Knows, Coms and Move — and the Okwe Knowledge imprint, with the rule that governs them. Vector masters are generated from the same numbers the components read, so what you download is what the system draws.",
  foot: "Vector is generated at build. Raster is rendered here, from the mark you are looking at.",
} as const;
